import { db } from './server/db';
import { airports } from './shared/schema';

const mockAirports = [
  // Major US Airports
  {
    id: "1",
    code: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    state: "CA",
    country: "United States",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    latitude: "33.9416",
    longitude: "-118.4085",
    createdAt: new Date(),
  },
  {
    id: "2",
    code: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    state: "NY",
    country: "United States",
    countryCode: "US",
    timezone: "America/New_York",
    latitude: "40.6413",
    longitude: "-73.7781",
    createdAt: new Date(),
  },
  {
    id: "3",
    code: "ORD",
    name: "Chicago O'Hare International Airport",
    city: "Chicago",
    state: "IL",
    country: "United States",
    countryCode: "US",
    timezone: "America/Chicago",
    latitude: "41.9786",
    longitude: "-87.9048",
    createdAt: new Date(),
  },
  {
    id: "4",
    code: "DFW",
    name: "Dallas/Fort Worth International Airport",
    city: "Dallas",
    state: "TX",
    country: "United States",
    countryCode: "US",
    timezone: "America/Chicago",
    latitude: "32.8968",
    longitude: "-97.0380",
    createdAt: new Date(),
  },
  {
    id: "5",
    code: "ATL",
    name: "Hartsfield-Jackson Atlanta International Airport",
    city: "Atlanta",
    state: "GA",
    country: "United States",
    countryCode: "US",
    timezone: "America/New_York",
    latitude: "33.6407",
    longitude: "-84.4277",
    createdAt: new Date(),
  },
  {
    id: "6",
    code: "MIA",
    name: "Miami International Airport",
    city: "Miami",
    state: "FL",
    country: "United States",
    countryCode: "US",
    timezone: "America/New_York",
    latitude: "25.7959",
    longitude: "-80.2870",
    createdAt: new Date(),
  },
  {
    id: "7",
    code: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    latitude: "37.6189",
    longitude: "-122.3750",
    createdAt: new Date(),
  },
  {
    id: "8",
    code: "LAS",
    name: "Harry Reid International Airport",
    city: "Las Vegas",
    state: "NV",
    country: "United States",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    latitude: "36.0840",
    longitude: "-115.1537",
    createdAt: new Date(),
  },
  {
    id: "9",
    code: "DEN",
    name: "Denver International Airport",
    city: "Denver",
    state: "CO",
    country: "United States",
    countryCode: "US",
    timezone: "America/Denver",
    latitude: "39.8561",
    longitude: "-104.6737",
    createdAt: new Date(),
  },
  {
    id: "10",
    code: "BOS",
    name: "Boston Logan International Airport",
    city: "Boston",
    state: "MA",
    country: "United States",
    countryCode: "US",
    timezone: "America/New_York",
    latitude: "42.3656",
    longitude: "-71.0096",
    createdAt: new Date(),
  },
  {
    id: "11",
    code: "SEA",
    name: "Seattle-Tacoma International Airport",
    city: "Seattle",
    state: "WA",
    country: "United States",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    latitude: "47.4502",
    longitude: "-122.3088",
    createdAt: new Date(),
  },
  {
    id: "12",
    code: "IAH",
    name: "George Bush Intercontinental Airport",
    city: "Houston",
    state: "TX",
    country: "United States",
    countryCode: "US",
    timezone: "America/Chicago",
    latitude: "29.9902",
    longitude: "-95.3368",
    createdAt: new Date(),
  },
  {
    id: "13",
    code: "MCO",
    name: "Orlando International Airport",
    city: "Orlando",
    state: "FL",
    country: "United States",
    countryCode: "US",
    timezone: "America/New_York",
    latitude: "28.4312",
    longitude: "-81.3081",
    createdAt: new Date(),
  },
  {
    id: "14",
    code: "PHX",
    name: "Phoenix Sky Harbor International Airport",
    city: "Phoenix",
    state: "AZ",
    country: "United States",
    countryCode: "US",
    timezone: "America/Phoenix",
    latitude: "33.4484",
    longitude: "-112.0740",
    createdAt: new Date(),
  },
  {
    id: "15",
    code: "EWR",
    name: "Newark Liberty International Airport",
    city: "Newark",
    state: "NJ",
    country: "United States",
    countryCode: "US",
    timezone: "America/New_York",
    latitude: "40.6895",
    longitude: "-74.1745",
    createdAt: new Date(),
  },
  // Major UK Airports
  {
    id: "16",
    code: "LHR",
    name: "London Heathrow Airport",
    city: "London",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "51.4700",
    longitude: "-0.4543",
    createdAt: new Date(),
  },
  {
    id: "17",
    code: "LGW",
    name: "London Gatwick Airport",
    city: "London",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "51.1537",
    longitude: "-0.1821",
    createdAt: new Date(),
  },
  {
    id: "18",
    code: "MAN",
    name: "Manchester Airport",
    city: "Manchester",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "53.3537",
    longitude: "-2.2750",
    createdAt: new Date(),
  },
  {
    id: "19",
    code: "STN",
    name: "London Stansted Airport",
    city: "London",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "51.8860",
    longitude: "0.2389",
    createdAt: new Date(),
  },
  {
    id: "20",
    code: "LTN",
    name: "London Luton Airport",
    city: "London",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "51.8747",
    longitude: "-0.3683",
    createdAt: new Date(),
  },
  {
    id: "21",
    code: "BHX",
    name: "Birmingham Airport",
    city: "Birmingham",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "52.4539",
    longitude: "-1.7480",
    createdAt: new Date(),
  },
  {
    id: "22",
    code: "EDI",
    name: "Edinburgh Airport",
    city: "Edinburgh",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "55.9500",
    longitude: "-3.3725",
    createdAt: new Date(),
  },
  {
    id: "23",
    code: "BRS",
    name: "Bristol Airport",
    city: "Bristol",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "51.3829",
    longitude: "-2.7179",
    createdAt: new Date(),
  },
  {
    id: "24",
    code: "NCL",
    name: "Newcastle Airport",
    city: "Newcastle",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "55.0375",
    longitude: "-1.6917",
    createdAt: new Date(),
  },
  {
    id: "25",
    code: "LPL",
    name: "Liverpool John Lennon Airport",
    city: "Liverpool",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "53.3336",
    longitude: "-2.8497",
    createdAt: new Date(),
  },
  {
    id: "26",
    code: "BFS",
    name: "Belfast International Airport",
    city: "Belfast",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "54.6575",
    longitude: "-6.2158",
    createdAt: new Date(),
  },
  {
    id: "27",
    code: "GLA",
    name: "Glasgow Airport",
    city: "Glasgow",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "55.8659",
    longitude: "-4.4331",
    createdAt: new Date(),
  },
  {
    id: "28",
    code: "CWL",
    name: "Cardiff Airport",
    city: "Cardiff",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "51.3967",
    longitude: "-3.3433",
    createdAt: new Date(),
  },
  {
    id: "29",
    code: "LCY",
    name: "London City Airport",
    city: "London",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "51.4700",
    longitude: "0.4543",
    createdAt: new Date(),
  },
  {
    id: "30",
    code: "ABZ",
    name: "Aberdeen Airport",
    city: "Aberdeen",
    state: "",
    country: "United Kingdom",
    countryCode: "GB",
    timezone: "Europe/London",
    latitude: "57.2019",
    longitude: "-2.1978",
    createdAt: new Date(),
  },
];

async function insertAirports() {
  try {
    console.log('Inserting airports...');
    
    for (const airport of mockAirports) {
      await db.insert(airports).values(airport);
      console.log(`Inserted airport: ${airport.code} - ${airport.name}`);
    }
    
    console.log('✅ All airports inserted successfully!');
  } catch (error) {
    console.error('❌ Error inserting airports:', error);
  } finally {
    process.exit(0);
  }
}

insertAirports(); 