import { db } from './server/db';
import { parkingLots } from './shared/schema';

const mockParkingLots = [
  // LHR Terminal 5 Official Parking (Supplier 1)
  {
    id: "1",
    supplierId: "supplier1",
    airportId: "airport_3", // LHR
    name: "LHR Terminal 5 Official Car Park",
    description: "Official Heathrow Terminal 5 parking with direct terminal access and covered parking",
    address: "Terminal 5, Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "0.1",
    shuttleFrequencyMinutes: 3,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: true,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 2500,
    imageUrl: "/images/lhr-terminal5-official.jpg",
    rating: "4.7",
    reviewCount: 1850,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    supplierId: "supplier1",
    airportId: "airport_3", // LHR
    name: "LHR Terminal 2 & 3 Official Car Park",
    description: "Official Heathrow Terminal 2 & 3 parking with 24/7 security",
    address: "Terminal 2 & 3, Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "0.2",
    shuttleFrequencyMinutes: 5,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 1800,
    imageUrl: "/images/lhr-terminal23-official.jpg",
    rating: "4.5",
    reviewCount: 1200,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Park & Fly UK (Supplier 2)
  {
    id: "3",
    supplierId: "supplier2",
    airportId: "airport_3", // LHR
    name: "LHR Meet & Greet Premium",
    description: "Premium meet & greet service - your car is collected at terminal",
    address: "Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "0.0",
    shuttleFrequencyMinutes: 0,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: true,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 500,
    imageUrl: "/images/lhr-meet-greet-premium.jpg",
    rating: "4.9",
    reviewCount: 750,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    supplierId: "supplier2",
    airportId: "airport_3", // LHR
    name: "LHR Park & Fly Express",
    description: "Fast shuttle service with covered parking and 24/7 security",
    address: "Bath Road, Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "0.8",
    shuttleFrequencyMinutes: 8,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 1200,
    imageUrl: "/images/lhr-park-fly-express.jpg",
    rating: "4.6",
    reviewCount: 980,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Airport Parking Solutions (Supplier 3)
  {
    id: "5",
    supplierId: "supplier3",
    airportId: "airport_3", // LHR
    name: "LHR Economy Parking",
    description: "Affordable uncovered parking with regular shuttle service",
    address: "Stanwell Moor Road, Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "1.5",
    shuttleFrequencyMinutes: 15,
    isShuttleIncluded: true,
    isCovered: false,
    hasEvCharging: false,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 2000,
    imageUrl: "/images/lhr-economy-parking.jpg",
    rating: "4.2",
    reviewCount: 650,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    supplierId: "supplier3",
    airportId: "airport_3", // LHR
    name: "LHR Long Stay Parking",
    description: "Long-term parking solution with secure facilities",
    address: "Long Stay Car Park, Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "2.0",
    shuttleFrequencyMinutes: 20,
    isShuttleIncluded: true,
    isCovered: false,
    hasEvCharging: false,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 3000,
    imageUrl: "/images/lhr-long-stay.jpg",
    rating: "4.0",
    reviewCount: 420,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Premium Parking Services (Supplier 4)
  {
    id: "7",
    supplierId: "supplier4",
    airportId: "airport_3", // LHR
    name: "LHR Valet Parking Premium",
    description: "Luxury valet parking with concierge service and car care",
    address: "Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "0.0",
    shuttleFrequencyMinutes: 0,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: true,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 200,
    imageUrl: "/images/lhr-valet-premium.jpg",
    rating: "4.9",
    reviewCount: 320,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    supplierId: "supplier4",
    airportId: "airport_3", // LHR
    name: "LHR Business Parking",
    description: "Business-focused parking with premium amenities and fast access",
    address: "Business Car Park, Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "0.3",
    shuttleFrequencyMinutes: 5,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: true,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 800,
    imageUrl: "/images/lhr-business-parking.jpg",
    rating: "4.7",
    reviewCount: 580,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Quick Park Heathrow (Supplier 5)
  {
    id: "9",
    supplierId: "supplier5",
    airportId: "airport_3", // LHR
    name: "LHR Quick Park Express",
    description: "Fast and convenient parking with 24/7 shuttle service",
    address: "Quick Park Express, Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "0.6",
    shuttleFrequencyMinutes: 6,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 1500,
    imageUrl: "/images/lhr-quick-park-express.jpg",
    rating: "4.4",
    reviewCount: 890,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    supplierId: "supplier5",
    airportId: "airport_3", // LHR
    name: "LHR Quick Park Budget",
    description: "Budget-friendly parking with reliable shuttle service",
    address: "Budget Car Park, Heathrow Airport, London, UK",
    latitude: "51.4700",
    longitude: "-0.4543",
    distanceToTerminal: "1.2",
    shuttleFrequencyMinutes: 12,
    isShuttleIncluded: true,
    isCovered: false,
    hasEvCharging: false,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 2500,
    imageUrl: "/images/lhr-quick-park-budget.jpg",
    rating: "4.1",
    reviewCount: 720,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // LAX Parking Lots (Airport ID: "1")
  {
    id: "14",
    supplierId: "supplier1",
    airportId: "airport_2", // LAX
    name: "LAX Official Parking Structure",
    description: "Official LAX parking structure with direct terminal access",
    address: "Los Angeles International Airport, Los Angeles, CA",
    latitude: "33.9416",
    longitude: "-118.4085",
    distanceToTerminal: "0.1",
    shuttleFrequencyMinutes: 0,
    isShuttleIncluded: false,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 3000,
    imageUrl: "/images/lax-official-parking.jpg",
    rating: "4.6",
    reviewCount: 2100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "15",
    supplierId: "supplier2",
    airportId: "airport_2", // LAX
    name: "LAX Economy Parking",
    description: "Budget-friendly parking with shuttle service to terminals",
    address: "LAX Economy Parking, Los Angeles, CA",
    latitude: "33.9416",
    longitude: "-118.4085",
    distanceToTerminal: "0.8",
    shuttleFrequencyMinutes: 8,
    isShuttleIncluded: true,
    isCovered: false,
    hasEvCharging: false,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 5000,
    imageUrl: "/images/lax-economy-parking.jpg",
    rating: "4.2",
    reviewCount: 1800,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "16",
    supplierId: "supplier3",
    airportId: "airport_2", // LAX
    name: "LAX Valet Parking Premium",
    description: "Premium valet service with car wash and detailing",
    address: "LAX Valet Parking, Los Angeles, CA",
    latitude: "33.9416",
    longitude: "-118.4085",
    distanceToTerminal: "0.0",
    shuttleFrequencyMinutes: 0,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: true,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 200,
    imageUrl: "/images/lax-valet-premium.jpg",
    rating: "4.8",
    reviewCount: 450,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "17",
    supplierId: "supplier4",
    airportId: "airport_2", // LAX
    name: "LAX Long Term Parking",
    description: "Secure long-term parking with 24/7 shuttle service",
    address: "LAX Long Term Parking, Los Angeles, CA",
    latitude: "33.9416",
    longitude: "-118.4085",
    distanceToTerminal: "1.2",
    shuttleFrequencyMinutes: 10,
    isShuttleIncluded: true,
    isCovered: false,
    hasEvCharging: false,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 8000,
    imageUrl: "/images/lax-long-term.jpg",
    rating: "4.3",
    reviewCount: 3200,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "18",
    supplierId: "supplier5",
    airportId: "airport_2", // LAX
    name: "LAX Quick Park Express",
    description: "Fast and convenient parking with express shuttle service",
    address: "LAX Quick Park, Los Angeles, CA",
    latitude: "33.9416",
    longitude: "-118.4085",
    distanceToTerminal: "0.5",
    shuttleFrequencyMinutes: 5,
    isShuttleIncluded: true,
    isCovered: true,
    hasEvCharging: true,
    hasCarWash: false,
    hasSecurityPatrol: true,
    hasCctv: true,
    totalSpaces: 1500,
    imageUrl: "/images/lax-quick-park.jpg",
    rating: "4.4",
    reviewCount: 950,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function insertParkingLots() {
  try {
    console.log('Inserting parking lots...');
    
    for (const lot of mockParkingLots) {
      await db.insert(parkingLots).values(lot);
      console.log(`Inserted parking lot: ${lot.name}`);
    }
    
    console.log('✅ All parking lots inserted successfully!');
  } catch (error) {
    console.error('❌ Error inserting parking lots:', error);
  } finally {
    process.exit(0);
  }
}

insertParkingLots(); 